# The pipeline for develop builds
name: mediafiles-release
trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  buildConfiguration: 'Release'

steps:
- template: steps-setup.yml
- template: steps-build.yml
- task: ArchiveFiles@2
  displayName: Create archive package
  inputs:
    rootFolderOrFile: 'ClientApp.Cli/bin/Release/netcoreapp3.1/win-x64/publish'
    includeRootFolder: false
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/mediafiles-$(MediaFilesVersion)-win-x64.zip'
    replaceExistingArchive: true    
- task: PublishPipelineArtifact@1
  displayName: Publish pipeline package
  inputs:
    targetPath: '$(Build.ArtifactStagingDirectory)/mediafiles-$(MediaFilesVersion)-win-x64.zip'
    artifact: 'mediafiles-dist'
    publishLocation: 'pipeline'
- task: PowerShell@2
  displayName: Build Chocolatey package
  inputs:
    targetType: 'inline'
    script: 'Invoke-Build Build-Package -PackageVersion $(MediaFilesVersion)'
- task: NuGetCommand@2
  displayName: Publish to the NuGet feed
  inputs:
    command: 'push'
    packagesToPush: 'artifacts/*.nupkg;'
    nuGetFeedType: 'internal'
    publishVstsFeed: 'f16e3e3f-c420-4b68-a707-00a361027c73/d381290c-74c5-412e-8f22-c09bc0b15971'
    verbosityPush: 'Normal'
